@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title "Умный Дом: Диаграмма конекста"

Person(user, "Пользователь", "Управляет умным домом через веб или мобильное приложения")
Person(admin, "Администратор", "Администрирует систему. Обрабатывает заявки. Назначает тех специалистов")
Person(tech, "Тех. Специалсит", "Устанавливает и обслуживает приборыы умного дома")

System_Boundary("SmartHomeSystem", "Система умного дома") {
    System(monolith, "Монолитное приложение", "Web приложение для управления умным домом")
}

System_Ext(devices, "Устройства умного дома", "Датчики отопления, конфиционеров, дверей, освещение и др.")

' Взимодействие пользователей с приложением
Rel_Down(user, monolith, "Управление умным домом")
Rel_Down(admin, monolith, "Администрирование устройст. Обработка заявок")
Rel_Down(tech, monolith, "Обслуживание умного дама")

' Взимодействие приборов с сервисами
Rel_Up(devices, monolith, "связь с утсройствами")


@enduml